project_id = "sienlnxwwdqnybugipdt"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.assign-role]
verify_jwt = false

[functions.bulk-validate-import]
verify_jwt = false

[functions.bulk-import-execute]
verify_jwt = false

[functions.export-users]
verify_jwt = false

[functions.zoom-webhook]
verify_jwt = false

[functions.generate-course-content]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.zoom-fetch-host-ids]
verify_jwt = false

[functions.course-applicant-import]
verify_jwt = false

[functions.applicant-webhook]
verify_jwt = false
