// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Use to verify connectivity to the app's MCP server.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@2.95.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function userClient(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool2({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's profile record (name, email, role, division, etc.).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const sb = userClient(ctx);
    const { data, error } = await sb.from("profiles").select("id, full_name, email, role, phone, timezone, division_id, branch_id, archived_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Profile not found for this user." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-my-courses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_courses_default = defineTool3({
  name: "list_my_courses",
  title: "List my courses",
  description: "List courses the signed-in user is enrolled in or teaching. Row visibility follows the app's access rules.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum rows to return. Default 25."),
    status: z2.string().optional().describe("Optional status filter (e.g. active, completed).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const sb = userClient(ctx);
    let q = sb.from("courses").select("id, name, status, division_id, teacher_id, start_date, end_date, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-schedule.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_schedule_default = defineTool4({
  name: "list_my_schedule",
  title: "List my weekly schedule",
  description: "List the signed-in user's weekly class schedule entries. Row visibility follows the app's access rules.",
  inputSchema: {
    day_of_week: z3.enum(["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]).optional().describe("Optional filter for a specific weekday."),
    limit: z3.number().int().min(1).max(200).optional().describe("Maximum rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ day_of_week, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const sb = userClient(ctx);
    let q = sb.from("schedules").select("id, day_of_week, teacher_local_time, student_local_time, duration_minutes, is_active, assignment_id, course_id").eq("is_active", true).order("day_of_week").order("teacher_local_time").limit(limit ?? 50);
    if (day_of_week) q = q.eq("day_of_week", day_of_week);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { schedules: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-students.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_students_default = defineTool5({
  name: "list_my_students",
  title: "List my students",
  description: "For a signed-in teacher, list active student-teacher assignments. Row visibility follows the app's access rules.",
  inputSchema: {
    limit: z4.number().int().min(1).max(200).optional().describe("Maximum rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const sb = userClient(ctx);
    const { data, error } = await sb.from("student_teacher_assignments").select("id, student_id, teacher_id, subject_id, status, duration_minutes, start_date, division_id, branch_id").eq("teacher_id", ctx.getUserId()).eq("status", "active").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { assignments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sienlnxwwdqnybugipdt";
var mcp_default = defineMcp({
  name: "aqt-lms-mcp",
  title: "Al Quran Time Academy LMS",
  version: "0.1.0",
  instructions: "Tools for the Al Quran Time Academy LMS. Every tool runs as the signed-in user, so results respect the app's role and division access rules. Use `echo` to verify connectivity, `get_my_profile` to identify the current user, `list_my_courses` / `list_my_schedule` / `list_my_students` to read the user's own academic data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    echo_default,
    get_my_profile_default,
    list_my_courses_default,
    list_my_schedule_default,
    list_my_students_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
